# Generated by Django 4.2.3 on 2023-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'App User', 'verbose_name_plural': 'App Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='app_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
